name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push event but only for the "master" branch
  push:
    branches: [ "master" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
      
        with:
          host: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USER }}
          KEY: ${{ secrets.SSH_KEY }}   
    
          script: |
            cd ~/Discord
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/id_rsa
            git pull origin master
            echo ${{secrets.PASS}} | sudo -S supervisorctl restart parroting-parrot
